--1)
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') AS "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE ASC;


--2)
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';


--3)
SELECT 
PROFESSOR_NAME AS "교수이름", 
SUBSTR(((TO_CHAR(SYSDATE, 'YYYYMMDD')) - ('19' || (SUBSTR(PROFESSOR_SSN, 1, 6)))), 1, 2) AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 나이 ASC;


--4)
SELECT SUBSTR(PROFESSOR_NAME, 2)
FROM TB_PROFESSOR;


--5)
SELECT STUDENT_NO, STUDENT_NAME, SUBSTR(TO_CHAR(ENTRANCE_DATE, 'YYYYMMDD'), 1, 4) AS "입학년", ('19' || SUBSTR(STUDENT_SSN, 1, 2)) AS "출생년"
FROM TB_STUDENT
WHERE SUBSTR(TO_CHAR(ENTRANCE_DATE, 'YYYYMMDD'), 1, 4) - ('19' || SUBSTR(STUDENT_SSN, 1, 2)) >= 20;


--6)
SELECT TO_CHAR(TO_DATE('2020-12-25', 'YYYY-MM-DD'), 'DAY') AS "크리스마스 요일"
FROM DUAL;


--7)
SELECT 
TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD'), 
TO_DATE('99/10/11', 'RR/MM/DD'), TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;
--YY를 쓸경우 SYSDATE를 기준으로 해당 세기를 적용함.
--RR을 쓸경우 50년을 기준으로 현세기와 전세기를 적용함.
--따라서 YY를 두 가지 TO_DATE는 2099년, 2049년을 의미하며
--RR을 쓴 두 가지 TO_DATE는 1999년 2049년을 의미한다


--8)
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';


--9)
SELECT ROUND(AVG(POINT), 1) AS "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';


--10)
SELECT DEPARTMENT_NO AS "학과번호", COUNT(STUDENT_NO) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;


--11)
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;


--12)
SELECT SUBSTR(TERM_NO, 1, 4) AS "년도", ROUND(AVG(POINT), 1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4);


--13)
--0명인 과가 제외됨. 해결해야함
SELECT DEPARTMENT_NO AS "학과번호", NVL(COUNT(STUDENT_NO), 0) AS "학생수(명)"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY 1;


--강사님 답
SELECT DEPARTMENT_NO 학과코드명, COUNT(DECODE(ABSENCE_YN, 'Y', 1)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;


--14)
SELECT STUDENT_NAME, COUNT(STUDENT_NAME)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) >= 2;


--15)
--해결 못함
SELECT "년도", "학기", POINT
FROM (SELECT SUBSTR(TERM_NO, 1, 4) AS "년도",SUBSTR(TERM_NO, 5, 2) AS "학기", POINT, STUDENT_NO, TERM_NO
      FROM TB_GRADE
      )
WHERE STUDENT_NO = 'A112113';

--해답
SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, 5, 2) 학기, ROUND(AVG(POINT), 1) 평균
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
ORDER BY 1;



